# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
parameters:
    my_user_provider.class: Application\Sonata\UserBundle\Security\Core\User\SonataUserProvider

services:
    my_user_provider:
        class: "%my_user_provider.class%"
        arguments: [@fos_user.user_manager,{vkontakte: vkontakte_id, facebook: facebook_id}]